blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ ë²„ê·¸ ë¦¬í¬íŠ¸
    description: ì˜ˆê¸°ì¹˜ ì•Šì€ ë¬¸ì œë‚˜ ì˜¤ë¥˜ë¥¼ ë³´ê³ í•©ë‹ˆë‹¤.
    labels: ["bug"]
    file: bug_report.md

  - name: âœ… í…ŒìŠ¤íŠ¸ í•„ìš”
    description: í…ŒìŠ¤íŠ¸ê°€ í•„ìš”í•œ ê¸°ëŠ¥ì´ë‚˜ ì¼€ì´ìŠ¤ë¥¼ ì œì•ˆí•©ë‹ˆë‹¤.
    labels: ["test"]
    file: test_required.md

  - name: â“ ì§ˆë¬¸
    description: ì½”ë“œ, í”„ë¡œì íŠ¸ ì‚¬ìš©ë²•, ê°œë°œ í™˜ê²½ ë“±ì— ëŒ€í•´ ì§ˆë¬¸í•©ë‹ˆë‹¤.
    labels: ["question"]
    file: question.md

  - name: ğŸ’¬ ë…¼ì˜
    description: ì•„ì´ë””ì–´ë‚˜ ì•„í‚¤í…ì²˜, ë°©í–¥ì„±ì— ëŒ€í•œ ë…¼ì˜ë¥¼ ì‹œì‘í•©ë‹ˆë‹¤.
    labels: ["discussion"]
    file: discussion.md

  - name: âœ¨ ê¸°ëŠ¥ êµ¬í˜„
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ì˜ êµ¬í˜„ ìš”ì²­ì´ë‚˜ ì œì•ˆì„ ì‘ì„±í•©ë‹ˆë‹¤.
    labels: ["enhancement"]
    file: feature_request.md